In [1]:
import pandas as pd
import numpy as np

## Loading in our dataset 

We are using the dataset from [GSE277334](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE277334) retrieved from the Gene Expression Omnibus (GEO). 

This contains 763 liver transplant biopsies classified into four molecular genotypes, characterized by their gene expression: No-rejection (NR) 54%; TCMR 16%; NKRL 13%; and Injury 16%. 

This dataset has been pre-processed with the microarray probe labels replaced with genes named, while microarray probes referencing the same gene has also been combined. The features (genes) with low gene expressions of a median less than 3 has been removed from the dataset. This results in 18645 features for this dataset.

We load in the new dataset and see what it looks like.

In [2]:
path = "../Checkpoint2_Microarray_Processing/GSE277334_expression_collapsed_filtered.csv"
path_target = "../Checkpoint2_Microarray_Processing/GSE277334_metadata.csv"

df = pd.read_csv(path)
target = pd.read_csv(path_target)

In [3]:
display(df.shape) # (18645, 764), where one column is for the "Gene Symbol"
display(target.shape) # (763, 2)

(18645, 764)

(763, 2)

In [4]:
display(df.columns)
display(df.describe())
display(df.head())

Index(['Gene Symbol', 'GSM8519505', 'GSM8519506', 'GSM8519507', 'GSM8519508',
       'GSM8519509', 'GSM8519510', 'GSM8519511', 'GSM8519512', 'GSM8519513',
       ...
       'GSM8520258', 'GSM8520259', 'GSM8520260', 'GSM8520261', 'GSM8520262',
       'GSM8520263', 'GSM8520264', 'GSM8520265', 'GSM8520266', 'GSM8520267'],
      dtype='object', length=764)

,GSM8519505,GSM8519506,GSM8519507,GSM8519508,GSM8519509,GSM8519510,GSM8519511,GSM8519512,GSM8519513,GSM8519514,...,GSM8520258,GSM8520259,GSM8520260,GSM8520261,GSM8520262,GSM8520263,GSM8520264,GSM8520265,GSM8520266,GSM8520267
count,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,...,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000,18645.000000
mean,6.279595,6.281209,6.278919,6.273522,6.264295,6.272180,6.283976,6.269283,6.298402,6.278320,...,6.307767,6.313048,6.305291,6.287401,6.295183,6.291115,6.290827,6.291875,6.339847,6.282816
std,2.028491,2.042245,2.016224,2.084042,2.061609,2.030182,2.040548,2.033097,2.017384,2.048672,...,2.030470,1.993861,2.055414,2.048679,2.049861,2.056548,2.063699,2.035499,1.971140,2.078561
min,2.990000,2.930000,2.800000,2.940000,2.890000,2.940000,2.860000,2.810000,2.890000,2.850000,...,2.910000,2.690000,2.840000,2.930000,2.830000,2.830000,2.940000,2.840000,2.780000,2.720000
25%,4.670000,4.650000,4.660000,4.580000,4.580000,4.635000,4.640000,4.640000,4.680000,4.635000,...,4.700000,4.740000,4.640000,4.655000,4.660000,4.645000,4.630000,4.680000,4.820000,4.590000
50%,5.990000,5.980000,6.030000,5.970000,5.975000,6.000000,5.990000,5.990000,6.020000,5.990000,...,6.020000,6.060000,6.030000,6.010000,6.020000,5.990000,6.010000,6.000000,6.070000,6.010000
75%,7.545000,7.555000,7.560000,7.610000,7.590000,7.560000,7.560000,7.545000,7.560000,7.560000,...,7.545000,7.540000,7.600000,7.550000,7.560000,7.560000,7.610000,7.535000,7.490000,7.625000
max,14.590000,14.540000,14.600000,14.520000,14.540000,14.630000,14.590000,14.610000,14.540000,14.580000,...,14.580000,14.540000,14.540000,14.570000,14.590000,14.550000,14.530000,14.550000,14.560000,14.560000

,Gene Symbol,GSM8519505,GSM8519506,GSM8519507,GSM8519508,GSM8519509,GSM8519510,GSM8519511,GSM8519512,GSM8519513,...,GSM8520258,GSM8520259,GSM8520260,GSM8520261,GSM8520262,GSM8520263,GSM8520264,GSM8520265,GSM8520266,GSM8520267
0,A1BG,13.100,13.07,13.160,13.120,13.370,13.290,13.240,12.980,13.010,...,13.210,13.33,13.370,13.500,12.690,12.970,13.060,12.980,11.75,12.940
1,A1CF,11.485,11.38,10.585,10.900,11.145,10.810,11.070,11.210,11.000,...,11.445,11.48,11.325,11.245,11.300,11.595,10.645,11.455,9.86,11.055
2,A2BP1,3.645,3.72,3.455,3.575,3.525,3.415,3.625,3.575,3.675,...,3.595,3.81,3.600,3.685,3.665,3.780,3.565,3.750,3.57,3.475
3,A2LD1,6.430,7.00,6.120,6.330,6.850,6.300,6.330,6.710,7.030,...,6.460,6.83,6.540,6.260,6.710,7.180,7.370,7.480,7.38,6.290
4,A2M,12.720,13.16,13.160,13.340,12.620,13.190,12.960,13.530,12.690,...,12.800,13.21,12.630,13.040,12.420,12.720,12.860,12.390,12.05,13.130

In [5]:
df.isna().sum()

Gene Symbol    1
GSM8519505     0
GSM8519506     0
GSM8519507     0
GSM8519508     0
              ..
GSM8520263     0
GSM8520264     0
GSM8520265     0
GSM8520266     0
GSM8520267     0
Length: 764, dtype: int64

Note we have one `NaN` in our list of gene symbols, we will address this later.

## Transpose our dataset

Note our rows are defined as the genes while our columns are our sample. We want to transpose it so that our genes are columns to represent our features.

In [6]:
df_temp = df.copy().set_index('Gene Symbol')
df_T = df_temp.T
print(df_T.head())
df_T.columns[-3:]

Gene Symbol   A1BG    A1CF  A2BP1  A2LD1    A2M  A2ML1  A3GALT2  A4GALT  \
GSM8519505   13.10  11.485  3.645   6.43  12.72  3.580     4.24   3.960
GSM8519506   13.07  11.380  3.720   7.00  13.16  3.310     4.21   4.175
GSM8519507   13.16  10.585  3.455   6.12  13.16  3.370     4.11   4.105
GSM8519508   13.12  10.900  3.575   6.33  13.34  3.270     4.24   4.130
GSM8519509   13.37  11.145  3.525   6.85  12.62  3.605     4.15   4.090

Gene Symbol  A4GNT   AAA1  ...   ZXDB   ZXDC  ZYG11A  ZYG11B    ZYX  ZZEF1  \
GSM8519505    5.13  3.615  ...  5.975  6.565   3.655   7.195  7.785  7.405
GSM8519506    4.88  3.545  ...  5.415  6.560   3.520   6.695  7.505  7.380
GSM8519507    4.92  3.545  ...  5.505  6.800   3.115   6.880  7.815  7.545
GSM8519508    4.73  3.480  ...  6.580  6.630   3.275   7.600  8.145  7.250
GSM8519509    4.74  3.460  ...  5.785  6.845   3.210   7.155  7.815  7.535

Gene Symbol   ZZZ3    NaN  selenoprotein 15  tAKR
GSM8519505   8.165  8.160            11.080  6.53
GSM8519506   8.120  8.095            11.115  6.80
GSM8519507   7.975  8.170            11.325  6.15
GSM8519508   7.825  8.145            11.175  7.23
GSM8519509   8.220  8.045            11.155  6.53

[5 rows x 18645 columns]

Index([nan, 'selenoprotein 15', 'tAKR'], dtype='object', name='Gene Symbol')

# Removing the NaN column

We see there is a column with name `NaN`, which corresponds to markers from the microarray that did not have an identifiable gene attached to it. We remove it below.

In [7]:
print(df_T.shape) # (763, 18645)
df_T = df_T.drop(columns=[np.nan])
print(df_T.shape) # (763, 18644)

df_T.columns[-3:] # We see our NaN label is now gone

(763, 18645)
(763, 18644)

Index(['ZZZ3', 'selenoprotein 15', 'tAKR'], dtype='object', name='Gene Symbol')

In [ ]:
# Checking we have no more NaN values anywhere. 
df_T.isna().sum().sum()

np.int64(0)

# Exploring the labels 

We want to see what our target labels are, and the distribution of each group.

In [30]:
display(target['Cluster'].value_counts())
display(target.head())

Cluster
NR        415
TCMR      125
Injury    125
NKRL       98
Name: count, dtype: int64

       Sample Cluster
0  GSM8519505      NR
1  GSM8519506    NKRL
2  GSM8519507    TCMR
3  GSM8519508  Injury
4  GSM8519509      NR

## Adjusting the labels 
The original labels used by the paper is defined by 
- NR: Non-rejection (non-rejection)       
- TCMR: T cell-mediated rejection (rejection)
- Injury (non-rejection)
- NKRL: NK cell-enriched rejection-like state (rejection)

We want to classify by rejection or non-rejections, so we changed them to be:
- 0: non-rejection  
- 1: rejection

In [29]:
target_adjusted = target.copy()

target_adjusted.loc[target['Cluster'].isin(['NR', 'Injury']), 'Cluster'] = 0
target_adjusted.loc[target['Cluster'].isin(['TCMR', 'NKRL']), 'Cluster'] = 1

target_adjusted.head()

       Sample Cluster
0  GSM8519505       0
1  GSM8519506       1
2  GSM8519507       1
3  GSM8519508       0
4  GSM8519509       0

## Split into Training and Testing set

Now that we have cleaned up our data, we will split into the training and test sets for further use.

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(df_T, target_adjusted, random_state=123, test_size=0.2)

Checking the split between the two groups remains proportional between the training and testing set.

In [21]:
print(y_train['Cluster'].value_counts())
print(y_test['Cluster'].value_counts())
print('\n')

print(y_train['Cluster'].value_counts(normalize=True))
print(y_test['Cluster'].value_counts(normalize=True))

Cluster
0    432
1    178
Name: count, dtype: int64
Cluster
0    108
1     45
Name: count, dtype: int64


Cluster
0    0.708197
1    0.291803
Name: proportion, dtype: float64
Cluster
0    0.705882
1    0.294118
Name: proportion, dtype: float64

In [31]:
X_train.to_csv('./X_train.csv')
X_test.to_csv('./X_test.csv')

y_train.to_csv('./y_train.csv', index=False)
y_test.to_csv('./y_test.csv', index=False)